"""empty message

Revision ID: 450bee42becc
Revises: fb46d8f77687
Create Date: 2025-02-28 09:15:22.286569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450bee42becc'
down_revision = 'fb46d8f77687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('msg_num', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('msg_num')

    # ### end Alembic commands ###
