"""empty message

Revision ID: 8589d8092e0d
Revises: 7a317a917215
Create Date: 2025-02-17 15:03:43.575082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8589d8092e0d'
down_revision = '7a317a917215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=mysql.TEXT(),
               type_=mysql.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=mysql.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
