name: CI with Docker Compose

on:
  push:
    branches: [eojin]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3307:3306
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: tarot_database
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: docker-compose -f docker-compose.yml up -d --build

    - name: Wait for Flask to be ready
      run: |
        echo "Waiting for Flask to be ready..."
        sleep 10

    - name: Run tests in container
      run: docker exec flask-app pytest --disable-warnings

    - name: Shut down Docker Compose
      run: docker-compose down
