name: Run Tests on Push to eojin Branch

on:
  push:
    branches: [eojin]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('app/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        pytest --disable-warnings
    
    - name: Set up Docker Compose
      run: docker-compose up -f docker-compose.yml -d --build

    - name: Wait for Flask to be ready
      run: |
        echo "Waiting for Flask to be ready...(7s)"
        sleep 7

    # - name: Run tests in container
    #   run: docker exec flask-app pytest --disable-warnings

    - name: Shut down Docker Compose
      run: docker-compose down

