name: Docker Build & Push

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build_and_push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2 # ap-northeast-2 서울 수정 필요

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin 099066653259.dkr.ecr.ap-southeast-2.amazonaws.com/flask-server

      - name: Build Docker image
        run: |
          docker build -t flask-server .
      
      - name: Tag Docker image for ECR
        run: |
          docker tag flask-server:latest 099066653259.dkr.ecr.ap-southeast-2.amazonaws.com/flask-server:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 099066653259.dkr.ecr.ap-southeast-2.amazonaws.com/flask-server:latest